# Generated by Django 4.1.7 on 2023-03-25 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionsRequest',
            fields=[
                ('request_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Applicant_Name', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=10)),
                ('District', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Pincode', models.IntegerField()),
                ('Ownership', models.CharField(max_length=50)),
                ('GovtID_Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewerDetails',
            fields=[
                ('Reviewer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Reviewer_Name', models.CharField(max_length=200)),
                ('Reviewer_Comments', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionsStatus',
            fields=[
                ('ID_Number', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=30)),
                ('Load_Applied', models.IntegerField()),
                ('Date_of_Application', models.DateTimeField()),
                ('Date_of_Approval', models.DateTimeField(blank=True, null=True)),
                ('Modified_Date', models.DateTimeField(blank=True, null=True)),
                ('Status', models.CharField(max_length=50)),
                ('Reviewer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity.reviewerdetails')),
                ('request_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity.connectionsrequest')),
            ],
        ),
    ]
